server:
  port: 8080
spring:
  #数据库连接配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.101:3306/mysql?characterEncoding=utf-8&useSSL=false
    username: root
    password: root

#mybatis的相关配置
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  #type-aliases-package: com.zhg.demo.mybatis.entity
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true

#redis的相关配置

#rabbitmq
  rabbitmq:
    host: 192.168.0.101 #RabbitServer ip
    port: 5672 #RabbitServer port
    username: root
    password: root
    publisher-confirms: true
    publisher-returns: true
    template.mandatory: true
    exchangeName: hvp_topic_default #自定义exchangeName